# Generated by Django 5.2.8 on 2025-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraste_alto', models.BooleanField(default=False)),
                ('tamaño_texto', models.CharField(max_length=20)),
                ('lector_activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControlContraste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraste_activado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControlTamañoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño_actual', models.CharField(max_length=20)),
                ('opciones', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('id_modulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecursosInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recursos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
    ]
