# Generated by Django 5.2.8 on 2025-12-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessInidadDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraste_activo', models.BooleanField(default=False)),
                ('tamanio_token', models.CharField(default='normal', max_length=50)),
                ('lectura_archivado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Accesibilidad Digital',
                'verbose_name_plural': 'Accesibilidades Digitales',
            },
        ),
        migrations.CreateModel(
            name='AccessInidadFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Accesibilidad Fiscal', max_length=200)),
            ],
            options={
                'verbose_name': 'Accesibilidad Fiscal',
                'verbose_name_plural': 'Accesibilidades Fiscales',
            },
        ),
        migrations.CreateModel(
            name='ControlTermnoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epidemia', models.CharField(max_length=200)),
                ('token_inmuno_actual', models.CharField(max_length=200)),
                ('inmuno_actual', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Control Término Texto',
                'verbose_name_plural': 'Controles Término Texto',
            },
        ),
        migrations.CreateModel(
            name='LocatorPortalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Localizador Portalia',
                'verbose_name_plural': 'Localizadores Portalia',
            },
        ),
        migrations.CreateModel(
            name='GestorRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_reunachio_juster', models.CharField(max_length=200)),
                ('accessinidad_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='accesibilidad.accessinidadfiscal')),
            ],
            options={
                'verbose_name': 'Gestor de Recursos',
                'verbose_name_plural': 'Gestores de Recursos',
            },
        ),
        migrations.CreateModel(
            name='RecurrentSubstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=200)),
                ('descriptores', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substores', to='accesibilidad.gestorrecursos')),
            ],
            options={
                'verbose_name': 'Subalmacén Recurrente',
                'verbose_name_plural': 'Subalmacenes Recurrentes',
            },
        ),
    ]
