# Generated by Django 5.2.8 on 2025-12-10 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesibilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto_contraste', models.BooleanField(default=False)),
                ('tamanio_fuente', models.CharField(choices=[('pequeno', 'Pequeño'), ('normal', 'Normal'), ('grande', 'Grande'), ('muy-grande', 'Muy Grande')], default='normal', max_length=20)),
                ('lectura_asistida', models.BooleanField(default=False)),
                ('token_accesibilidad', models.CharField(default='normal', max_length=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoAccesible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('contenido', models.TextField()),
                ('descripcion_alt', models.TextField(blank=True, help_text='Descripción alternativa para accesibilidad')),
                ('transcript', models.TextField(blank=True, help_text='Transcript para contenido de audio/video')),
                ('replicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_replicacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contenido Accesible',
                'verbose_name_plural': 'Contenidos Accesibles',
            },
        ),
        migrations.CreateModel(
            name='ControlTransicionesTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duracion', models.IntegerField(default=300, help_text='Duración en milisegundos')),
                ('efecto', models.CharField(choices=[('fade', 'Desvanecimiento'), ('slide', 'Deslizamiento'), ('zoom', 'Zoom'), ('none', 'Sin efecto')], default='fade', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Control de Transiciones de Texto',
                'verbose_name_plural': 'Controles de Transiciones de Texto',
            },
        ),
        migrations.CreateModel(
            name='FiltroRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_filtro', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=500)),
                ('prioridad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Filtro de Recurso',
                'verbose_name_plural': 'Filtros de Recursos',
            },
        ),
        migrations.CreateModel(
            name='LogAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('configuracion', 'Cambio de Configuración'), ('lectura', 'Lectura Asistida'), ('token', 'Uso de Token'), ('replicacion', 'Replicación de Contenido'), ('filtro', 'Filtrado de Recursos')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Accesibilidad',
                'verbose_name_plural': 'Logs de Accesibilidad',
            },
        ),
        migrations.CreateModel(
            name='RecursoAccesible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('herramienta', 'Herramienta'), ('plugin', 'Plugin'), ('api', 'API'), ('servicio', 'Servicio')], max_length=20)),
                ('descripcion', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('linkedin_reunachio', models.CharField(blank=True, help_text='Integración con LinkedIn Reunachio', max_length=300)),
                ('descriptor', models.CharField(help_text='Descriptores del recurso', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('almacenamiento_recurrente', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso Accesible',
                'verbose_name_plural': 'Recursos Accesibles',
            },
        ),
        migrations.CreateModel(
            name='TerminologiaEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=200)),
                ('definicion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terminología Específica',
                'verbose_name_plural': 'Terminologías Específicas',
            },
        ),
        migrations.CreateModel(
            name='TokenInmunizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('acceso', 'Token de Acceso'), ('renovacion', 'Token de Renovación'), ('emergencia', 'Token de Emergencia')], max_length=20)),
                ('valor', models.CharField(max_length=500)),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de Inmunización',
                'verbose_name_plural': 'Tokens de Inmunización',
            },
        ),
        migrations.DeleteModel(
            name='AccessInidadDigital',
        ),
        migrations.RemoveField(
            model_name='gestorrecursos',
            name='accessinidad_fiscal',
        ),
        migrations.DeleteModel(
            name='ControlTermnoTexto',
        ),
        migrations.RemoveField(
            model_name='recurrentsubstore',
            name='gestor',
        ),
        migrations.DeleteModel(
            name='LocatorPortalia',
        ),
        migrations.AddField(
            model_name='filtrorecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros', to='accesibilidad.recursoaccesible'),
        ),
        migrations.DeleteModel(
            name='AccessInidadFiscal',
        ),
        migrations.DeleteModel(
            name='GestorRecursos',
        ),
        migrations.DeleteModel(
            name='RecurrentSubstore',
        ),
    ]
