# Generated by Django 5.2.8 on 2025-12-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('comision', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ame', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('sostenimiento', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('carton', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('regimen_adaptivo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='NivelDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=100)),
                ('categoria', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nivel Docente',
                'verbose_name_plural': 'Niveles Docentes',
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensums',
            },
        ),
        migrations.CreateModel(
            name='DocenteSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.IntegerField()),
                ('codigo_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='calificaciones.docente')),
            ],
            options={
                'verbose_name': 'Salario Docente',
                'verbose_name_plural': 'Salarios Docentes',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=200)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
                ('nota3', models.IntegerField()),
                ('existencia_sumativa', models.IntegerField()),
                ('fecha_registro', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_asignadas', to='calificaciones.docente')),
                ('codigo_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.estudiante')),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.pensum')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
