# Generated by Django 5.2.8 on 2025-11-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amie', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('sostenimiento', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('canton', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('regimen_educativo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
                ('grado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField()),
                ('año_lectivo', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
                ('nota3', models.IntegerField()),
                ('evaluacion_sumativa', models.IntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cedula_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.paralelo')),
            ],
        ),
    ]
